parameters: {}
environment: {}
packages:
    - name: functions
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: todos
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          parameters: {}
          environment:
            DATABASE_URL: "${dev.DATABASE_URL}"
          annotations: {}
          limits: {}
