packages:
    - name: functions
      shared: false
      functions:
        - name: todos
          binary: false
          web: true
          environment:
            DB_USER: "${DB_USER}"
            DB_PASSWORD: "${DB_PASSWORD}"
            DB_HOST: "${DB_HOST}"
            DB_NAME: "${DB_NAME}"
            DB_PORT: "${DB_PORT}"
